---
# Purpose: bring the instance to the desired state by running the role under test.
# Molecule calls this playbook with `molecule converge`.
- name: Converge
  hosts: all
  gather_facts: false # Disable if your role does not rely on facts
  pre_tasks:
    - name: Gather facts
      ansible.builtin.setup:
        gather_subset:
          - "!all"
          - "!min"
          - "hardware"
          - "env"
  roles:
    - name: Install oh-my-zsh
      role: ansible-oh-my-zsh
      backup_zshrc: false
